### ISSUE TITLE
tag the master branch

### ISSUE THREAD

**Issue by pocin** [tuomur/python-odata#16]
could you tag the "stable" master branch with some tags? That we we can use pip to install

`pip install --upgrade --no-cache-dir --ignore-installed https://github.com/pocin/python-odata/archive/v0.1.0.zip`

**Comment by tuomur** [comment]
pip can install from git directly:
`pip install git+https://github.com/tuomur/python-odata#egg=odata`

but that obviously gives your the master branch version. I'll take a look at using releases.

**Comment by tuomur** [comment]
[Tagged.](https://github.com/tuomur/python-odata/releases/tag/v0.2)
