### ISSUE TITLE
No entities returned on calling ODataService.

### ISSUE THREAD

**Issue by ankitjha97** [tuomur/python-odata#20]
I  am getting a dictionary with no entities on executing
`Service = ODataService(URL, auth=my_auth, reflect_entities = True)`
`Service.entities`

What could be the possible reasons for this?

**Comment by tuomur** [comment]
Metadata probably contains something python-odata doesn't understand. Can you link/attach the metadata xml here?

**Comment by ankitjha97** [comment]
@tuomur , here is the JSON data. It's not the metadata though.

{
	"d": {
		"results": [
			{
				"__metadata": {
					"type": "MLW_RESOURCES.CONTENTType",
		"uri":"http://mlbooks:8001/MLW/resources/JOINED..xsodata/CONTENT(BOOKS='1',NAME='LINEAR ALGEBRA')"
				},
				"BOOKS": "1",
				"NAME": "LINEAR ALGEBRA"
			}
		]
	}
}

Please ignore the indentation.
P.S : You can use the some JSON beautifier for it. The link is: https://codebeautify.org/jsonviewer

**Comment by tuomur** [comment]
That looks like OData 2.0 structure. python-odata supports only 4.0.

**Comment by ankitjha97** [comment]
Thanks. I am closing the issue with one question:
@tuomur , is there any package which I can use to access the data using OData services?

**Comment by tuomur** [comment]
No idea. I'd just use plain old Requests to get/post json.
