### ISSUE TITLE
Update README to include how to use it with Dynamics 2016

### ISSUE THREAD

**Issue by awartani** [tuomur/python-odata#5]
I came to this while trying to integrate it with Microsoft Dynamics 2016 and couldn't figure how to connect to it, because `ODataService` had auth param it was easy to integrate Dynamics authentication with it, simply use `HttpNtlmAuth`. 

```
import requests

auth_username = ''
auth_password = ''
basic_url = ''
odata_url = ''

session = requests.Session()
session.auth = HttpNtlmAuth(auth_username, auth_password, session)
session.get(basic_url) # should return 200

service = ODataService(odata_url, reflect_entities=True, session=session)
```

We noticed that after `HttpNtlmAuth` request, it was redirected to `/adfs/ls` page to perform `wsignin1` request. I don't know much about Dynamics nor Microsoft standers but I am happy to share the code if somebody needs it.

**Comment by tuomur** [comment]
Added this example to the docs. Thanks :)
