### ISSUE TITLE
can https be used?

### ISSUE THREAD

**Issue by allox** [tuomur/python-odata#7]
Is https supported?  
it always returns an empty list **{}** when I use it with python-odata

(example url:  https://services.odata.org/V4/Northwind/Northwind.svc/ )

**Comment by tuomur** [comment]
That site seems to have problems with its certificate. My tests just return `odata.exceptions.ODataConnectionError: hostname 'services.odata.org' doesn't match either of '*.azurewebsites.net', '*.scm.azurewebsites.net', '*.azure-mobile.net', '*.scm.azure-mobile.net'` when trying to use it.

**Comment by allox** [comment]
ok. that was just an example. 
Having the same issue with other https that I tested (sorry, not publicly available yet)

**Comment by tuomur** [comment]
It should work, python-odata doesn't really care if you're using http or https. The underlying library Requests handles all connectivity. If you receive empty results (no exceptions from requests, that is) then I'd say https is working.

**Comment by awartani** [comment]
https is working at my end, we have been using it on Production for a while without any issue.
